<?php
/**
 * Copyright 2015 Steerfox SAS.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * @author    Steerfox <tech@steerfox.com>
 * @copyright 2015 Steerfox SAS
 * @license   http://www.apache.org/licenses/LICENSE-2.0
 */
$steerfox_helper = Mage::helper('steerfox_plugins');
?>
<div class="panel steerfox-panel">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-4">
            <div class="row">
                <div class="col-xs-12 text-center">
                    <img class="img-responsive" style="margin:auto; max-width: 100%"
                         src="<?php echo $this->getSkinUrl('images/steerfox/steerfox-logo.png'); ?>"/>
                </div>

                <div class="col-xs-12 text-center">
                    <hr/>
                    <h2><?php echo $this->__('Configuration dashboard'); ?></h2>
                    <h4>
                        <?php echo $this->__('Configuration checklist for your Steerfox module.'); ?>
                    </h4>
                </div>
            </div>
        </div>

        <div class="col-xs-12 col-sm-6 col-md-8">
            <?php if (isset($checklist) && !empty($checklist)) { ?>
            <div class="table-responsive">
                <table class="table table-striped table-steerfoxcheck" cellpadding="0" cellspacing="0">
                    <tr>
                        <th><?php echo $this->__('Setting indicator'); ?></th>
                        <th class="text-center"><?php echo $this->__('Status'); ?></th>
                    </tr>
                    <?php foreach ($checklist as $key => $value) { ?>
                    <tr>
                        <td><?php print $value['title'] ?></td>
                        <td class="text-center">
                            <?php if (isset($value['state']) && $value['state'] == true) : ?>
                            <img src="<?php echo $this->getSkinUrl('images/success-msg.png'); ?>" alt="<?php echo $this->__('Enabled'); ?>" />
                            <?php else : ?>
                                <img src="<?php echo $this->getSkinUrl('images/error-msg.png'); ?>" alt="<?php echo $this->__('Disabled'); ?>" />
                            <?php endif; ?>
                            <?php /*/ ?>
                            <img src="../img/admin/{if isset($value['state']) && $value['state'] == true}enabled.gif{else}disabled.gif{/if}"
                                 alt="{if $tr.$key}<?php echo $this->__('Enabled'); ?>{else}<?php echo $this->__('Disabled'); ?>{/if}"
                                 title="{if $tr.$key}<?php echo $this->__('Enabled'); ?>{else}<?php echo $this->__('Disabled'); ?>{/if}"/>
                            <?php /**/ ?>
                        </td>
                    </tr>
                    <?php } ?>
                </table>
            </div>
            <?php } else { ?>
            <i>
                <?php echo $this->__('No checklist available for the moment.'); ?><br/>
                <?php echo $this->__('If the problem persist, please contact Steerfox : '); ?>
                <strong><?php echo $this->__('contact@steerfox.com'); ?></strong>
            </i>
            <?php } ?>

            <div class="row">
                <div class="col-xs-12 text-center mtop-20">
                    <a href="<?php print $steerfox_helper->getDashboardAction(); ?>" target="_blank" role="button"
                       class="btn btn-lg btn-primary btn-steerfox"><?php echo $this->__('My ads control panel'); ?></a>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 text-center mtop-20">
                    <hr />
                    <h4><?php echo $this->__('To access the magento module configuration you have to be in a website context.'); ?></h4>
                </div>
            </div>
        </div>
    </div>
</div>