<?php
$facebookId = $this->getFacebookId();
$currentProduct = $this->getCurrentProduct();
$productAddToCart = $this->getFacebookProductAddToCart();

if (!empty($facebookId)):
?>
    <!-- Facebook Pixel Code -->
    <script>
        !function (f, b, e, v, n, t, s) {
            if (f.fbq)return;
            n = f.fbq = function () {
                n.callMethod ?
                    n.callMethod.apply(n, arguments) : n.queue.push(arguments)
            };
            if (!f._fbq)f._fbq = n;
            n.push = n;
            n.loaded = !0;
            n.version = '2.0';
            n.queue = [];
            t = b.createElement(e);
            t.async = !0;
            t.src = v;
            s = b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t, s)
        }(window,
            document, 'script', '//connect.facebook.net/en_US/fbevents.js');
        fbq('init', '<?php echo $facebookId; ?>');
        fbq('track', "PageView");

        <?php if (null !== $currentProduct):
            $categories = $currentProduct->getCategoryIds();
            $catName = null;
            if (0 < count($categories)) {
                $category = Mage::getModel('catalog/category')->load($categories[0]);
                $catName = $category->getName();
            }?>
        fbq('track', 'ViewContent', {
            content_name : '<?php echo $currentProduct->getName(); ?>',
            content_category : '<?php echo $catName; ?>',
            content_ids : ['<?php echo $currentProduct->getId(); ?>'],
            content_type : 'product',
            value: '<?php echo $currentProduct->getPrice(); ?>',
            currency: '<?php echo $this->getCurrencyCode(); ?>'
        });
        <?php endif; ?>


        <?php if (is_array($productAddToCart) && 0 < count($productAddToCart)) : ?>
        fbq('track', 'AddToCart', {
            content_name: '<?php echo $productAddToCart['name']; ?>',
            content_category: '<?php echo $productAddToCart['cat']; ?>',
            content_ids: ['<?php echo $productAddToCart['id']; ?>'],
            content_type: 'product',
            value: '<?php echo $productAddToCart['price']; ?>',
            currency: '<?php echo $this->getCurrencyCode(); ?>'
        });
        <?php endif; ?>

    </script>
    <noscript>
        <img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=<?php echo $facebookId; ?>&ev=PageView&noscript=1"/>
    </noscript>
    <!-- End Facebook Pixel Code -->
<?php endif; ?>
