<!-- GTM tracking -->
<?php
    $gtmId = $this->getGtmId();
    if (!empty($gtmId)) :
?>
    <?php
        $order = $this->getOrder();
        if (!empty($order)) : ?>
        <script type="text/javascript">
            dataLayer=[{
                    'conversionLanguage': '<?php echo $this->getLocaleCode(); ?>',
                    'conversionTotal': '<?php echo $this->getConvertionAmount($order); ?>',
                    'conversionCurrency': '<?php echo $order->getOrderCurrencyCode(); ?>'
                }];
        </script>

    <?php endif; ?>
    <!-- Google Tag Manager -->
    <noscript><iframe src="//www.googletagmanager.com/ns.html?id=<?php echo $gtmId;?>"
                      height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','<?php echo $gtmId;?>');</script>
    <!-- End Google Tag Manager -->
<?php endif; ?>
